### ISSUE TITLE
NineGridView

### ISSUE THREAD

**Issue by iielse** [KCrason/HighPerformanceFriendsCircle#1]
193行至197行
```
view.setOnClickListener(v -> {
    if (mListener != null) {
        mListener.onImageClick(position, view);
    }
});
```
改成
```
if (mListener != null) {
    view.setOnClickListener(v -> {
        if (mListener != null) {
            mListener.onImageClick(position, view);
        }
    });
}
```

在没有设置图片点击回调的时候，不消耗itemView的点击事件

**Comment by wuaoke** [comment]
这样改是否考虑条目复用？会不会造成条目点击事件混乱？

**Comment by KCrason** [comment]
他这样改对点击事件的混乱是没有影响的，因为mListener == null就判断此时是不设置点击事件，也就不存在混乱的情况。而如果mListener != null，则必然还是会设置点击事件的。只有在有的条目设置了，有的条目没设置才会出现adapter复用时出现混乱情况。

当然他这个改动的目的本身是针对不设置点击事件的情况对性能的损耗问题。从某种程度上讲，这种损耗是可以忽略的。

**Comment by KCrason** [comment]
这样改是不会造成点击事件的混乱的。因为当mListener == null时，根本没有设置任何一个点击事件，而当mListener != null时，所有的item都设置了点击事件。在adapter复用时，只有有些item设置了点击事件有些item未设置点击事件才会造成点击事件的混乱。

事实上，他这样的目的只是为了在不设置点击事件时避免多余的点击消耗。意义有，但不大。

**Comment by iielse** [comment]
@KCrason 如果不这样改，按压在图片上时无法触发 整体条目的背景变色，和响应点击事件跳转页面。不过这是小事，核心的还是 View复用的实现。
